name: game_boy_graphics_editor
description: Edit GBDK graphics source files

version: 1.0.1+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  file_picker: ^6.2.0
  contextmenu: ^3.0.0
  image: ^4.1.0
  flutter_bloc: ^8.1.0
  replay_bloc: ^0.2.0
  two_dimensional_scrollables: ^0.1.2
  shared_preferences: ^2.2.0
  path: ^1.8.3
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Variable.ttf
